import { Router } from "express";
import { requireAdminAuth } from "./middleware/auth";
import { attachAdminTenantContext, attachPublicTenantContext } from "./middleware/tenant";
import { healthRoutes } from "./modules/health/routes";
import { authRoutes } from "./modules/auth/routes";
import { whatsappRoutes } from "./modules/integrations/whatsapp.routes";
import { enquiryRoutes } from "./modules/enquiries/routes";
import { vendorRoutes } from "./modules/vendors/routes";
import { vendorResponseRoutes } from "./modules/vendors/vendor-response.routes";
import { quoteRoutes } from "./modules/quotes/routes";
import { proposalRoutes } from "./modules/proposals/routes";
import { proposalPublicRoutes } from "./modules/proposals/public.routes";
import { paymentRoutes } from "./modules/payments/routes";
import { paymentWebhookRoutes } from "./modules/payments/webhook.routes";
import { bookingRoutes } from "./modules/bookings/routes";
import { conversationRoutes } from "./modules/conversations/routes";
import { auditRoutes } from "./modules/audit/routes";
import { tenantRoutes } from "./modules/tenants/routes";
import { dashboardRoutes } from "./modules/dashboard/routes";
import { emailRoutes } from "./modules/emails/routes";
import { emailWebhookRoutes } from "./modules/emails/webhook.routes";

export const router = Router();

router.use("/health", healthRoutes);
router.use("/auth", authRoutes);
router.use("/webhooks/:tenantSlug/whatsapp", attachPublicTenantContext, whatsappRoutes);
router.use("/webhooks/whatsapp", attachPublicTenantContext, whatsappRoutes);
router.use("/webhooks/:tenantSlug/vendor-responses", attachPublicTenantContext, vendorResponseRoutes);
router.use("/webhooks/vendor-responses", attachPublicTenantContext, vendorResponseRoutes);
router.use("/webhooks/:tenantSlug/emails", attachPublicTenantContext, emailWebhookRoutes);
router.use("/webhooks/emails", attachPublicTenantContext, emailWebhookRoutes);
router.use("/payments/webhook/:tenantSlug", attachPublicTenantContext, paymentWebhookRoutes);
router.use("/payments/webhook", attachPublicTenantContext, paymentWebhookRoutes);
router.use("/proposals", proposalPublicRoutes);
router.use("/payments", requireAdminAuth, attachAdminTenantContext, paymentRoutes);
router.use("/tenants", requireAdminAuth, attachAdminTenantContext, tenantRoutes);
router.use("/dashboard", requireAdminAuth, attachAdminTenantContext, dashboardRoutes);
router.use("/enquiries", requireAdminAuth, attachAdminTenantContext, enquiryRoutes);
router.use("/vendors", requireAdminAuth, attachAdminTenantContext, vendorRoutes);
router.use("/quotes", requireAdminAuth, attachAdminTenantContext, quoteRoutes);
router.use("/proposals", requireAdminAuth, attachAdminTenantContext, proposalRoutes);
router.use("/bookings", requireAdminAuth, attachAdminTenantContext, bookingRoutes);
router.use("/conversations", requireAdminAuth, attachAdminTenantContext, conversationRoutes);
router.use("/audit-logs", requireAdminAuth, attachAdminTenantContext, auditRoutes);
router.use("/emails", requireAdminAuth, attachAdminTenantContext, emailRoutes);
